string = "Hello World"
inteiro = 20
float_n = 20.5 #números decimais
complexo = 13j #números complexos
lista = ["apple", "banana", "cherry"]
tupla = ("apple", "banana", "cherry")
range_ = range(6)
dicio = {"name" : "John", "age" : 36}
set_ = {"apple", "banana", "cherry", 'cherry'} #não tem ordem, os itens aparecem aleatoriamente, ele também remove duplicas
frozenset_ = frozenset({"apple", "banana", "cherry", 'cherry'})
boolean = True
bytes_ = b"Hello"
bytearray_ = bytearray(3)
memoryview_ = memoryview(bytearray_)
noneType = None